# Generated by Django 5.1.5 on 2025-02-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedSearch',
            fields=[
                ('search_query', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('results', models.JSONField()),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
